### PR TITLE
Logo img

### LINKED ISSUE #11: [FEAT] repo logo
**Is your feature request related to a problem? Please describe.**
We need a logo for our repo :) 

Up to you and your imagination. Anything that is related to the context (Clash Royale and chests) is fine!

**Additional context**
Image should have at least 1024px width.

### PR DESCRIPTION
**Pull request by pratik2315**
hey there andre. right now im quite confused as to what the right logo should be. so i will link down 2 prs in which i have used two diff logos. can you pls suggest changes to them.

Fixes #11

### CODE REVIEW

**Comment by AndreVarandas** [comment]
@pratik2315 thanks for your help! Tbh, I like both of them! 👍 

I find the second one more colorful, but the first one plays better with the theme, so I leave it up to you!

Could you also create a folder named `extra` at the root of the project and add your images there? (I can also do that later if it's not convenient for you right now)

**Comment by pratik2315** [comment]
Hey sure

**Comment by pratik2315** [comment]
Hey @AndreVarandas ! After much thought, I have decided to add the first logo. I agree with you that the logo theme matches with the repo better.

**Comment by pratik2315** [comment]
I have also created a folder called extra and added images to them

**Comment by AndreVarandas** [comment]
Thank you for your awesome help here @pratik2315! We might find a use for both of the logos 👍

**Comment by pratik2315** [comment]
Thanks for the help. Hopefully I'll get to work with you soon :)

**Pull request merged**
