### PR TITLE
added image for social media previews

### LINKED ISSUE #10: [FEAT] add social preview image
**Is your feature request related to a problem? Please describe.**
Upload an image to customize your repository’s social media preview. (Can be based on our README.md logo)

Images should be at least 640×320px (1280×640px for best display).

**Additional context**
Can also use the attached template below:

repository-open-graph-template

### PR DESCRIPTION
**Pull request by pratik2315**
Fixes #10 

- Added the image for social media previews under the `extra` folder

### CODE REVIEW

**Comment by pratik2315** [comment]
Hey @AndreVarandas !
Can you check if the image is proper?

here's the image (1280×640px version):
social-preview-image

**Comment by AndreVarandas** [comment]
Screenshot 2022-10-30 at 13 40 33

Looking great @pratik2315 ! Thanks a lot for your help 🚀

**Comment by AndreVarandas** [comment]
This can be previewed at [https://socialsharepreview.com/?url=https://github.com/AndreVarandas/chest-tracker-for-cr](https://socialsharepreview.com/?url=https://github.com/AndreVarandas/chest-tracker-for-cr)

**Comment by pratik2315** [comment]
Thanks a lot @AndreVarandas 😄💪!

**Pull request merged**
